import {useEffect,useMemo,useState} from 'react'
import {useNavigate,useParams} from 'react-router-dom'
import Entity from '../components/Entity'
import HUD from '../components/HUD'
import {fallbackLevel} from '../data/fallbackLevel'
import {getLevel} from '../services/api'
const key=(x,y)=>x+'-'+y
export default function Game(){const{level}=useParams();const navigate=useNavigate();const[data,setData]=useState(null);const[loading,setLoading]=useState(true);const[apiError,setApiError]=useState(false);const[player,setPlayer]=useState(fallbackLevel.player);const[lives,setLives]=useState(3);const[enemies,setEnemies]=useState(fallbackLevel.enemies);const[hasKey,setHasKey]=useState(false);const[time,setTime]=useState(60);const alias=sessionStorage.getItem('playerAlias')||'Ashen'
useEffect(()=>{getLevel(level).then(r=>{setData(r);setPlayer(r.player);setEnemies(r.enemies);setTime(r.timeLimit)}).catch(()=>setApiError(true)).finally(()=>setLoading(false))},[level])
const lvl=data||fallbackLevel;const walls=useMemo(()=>new Set(lvl.walls.map(w=>key(w.x,w.y))),[lvl])
function finish(result){const runId=crypto.randomUUID();const score=Math.max(0,time*10+(3-enemies.length)*100-(3-lives)*50);sessionStorage.setItem('run-'+runId,JSON.stringify({runId,alias,score,time,result,enemiesDefeated:3-enemies.length,damage:3-lives}));navigate('/results/'+runId)}
useEffect(()=>{if(loading)return;const t=setInterval(()=>setTime(v=>Math.max(0,v-1)),1000);return()=>clearInterval(t)},[loading])
useEffect(()=>{if(lives<=0||time<=0)finish('defeat')},[lives,time])
useEffect(()=>{function move(e){const d={w:[0,-1],arrowup:[0,-1],s:[0,1],arrowdown:[0,1],a:[-1,0],arrowleft:[-1,0],d:[1,0],arrowright:[1,0]}[e.key.toLowerCase()];if(!d)return;e.preventDefault();setPlayer(p=>{const n={x:p.x+d[0],y:p.y+d[1]};if(n.x<0||n.y<0||n.x>=lvl.width||n.y>=lvl.height||walls.has(key(n.x,n.y)))return p;const hit=enemies.find(x=>x.x===n.x&&x.y===n.y);if(hit){setLives(v=>Math.max(0,v-1));setEnemies(v=>v.filter(x=>x.id!==hit.id));return p}if(n.x===lvl.key.x&&n.y===lvl.key.y)setHasKey(true);if(hasKey&&n.x===lvl.exit.x&&n.y===lvl.exit.y)finish('victory');return n})}window.addEventListener('keydown',move);return()=>window.removeEventListener('keydown',move)},[lvl,walls,enemies,hasKey])
if(loading)return <main className="screen center"><section className="panel"><p className="eyebrow">LOADING</p><h1>Abriendo la cripta...</h1></section></main>
return <main className="screen game-screen">{apiError&&<div className="api-notice">JSON Server no disponible. Usando nivel local de respaldo.</div>}<HUD alias={alias} lives={lives} time={time} enemies={enemies.length}/><section className="game-layout"><div className="dungeon" style={{gridTemplateColumns:'repeat('+lvl.width+',1fr)'}}>{Array.from({length:lvl.width*lvl.height},(_,i)=>{const x=i%lvl.width,y=Math.floor(i/lvl.width),wall=walls.has(key(x,y)),isPlayer=player.x===x&&player.y===y,enemy=enemies.find(e=>e.x===x&&e.y===y),isKey=lvl.key.x===x&&lvl.key.y===y&&!hasKey,isExit=lvl.exit.x===x&&lvl.exit.y===y;return <div key={key(x,y)} className={'tile '+(wall?'wall':'')}>{isPlayer&&<Entity type="player" label="Jugador"/>}{!isPlayer&&enemy&&<Entity type="enemy" label="Enemigo"/>}{!isPlayer&&!enemy&&isKey&&<Entity type="key" label="Llave"/>}{!isPlayer&&!enemy&&!isKey&&isExit&&<Entity type="exit" label="Salida"/>}</div>})}</div><aside className="panel instructions"><p className="eyebrow">ASHEN CRYPT</p><h2>Objetivo</h2><p>Usa WASD o las flechas. Consigue la llave y llega a X.</p><p>Al tocar un enemigo recibes daño y el enemigo desaparece.</p></aside></section></main>}